from _typeshed import Incomplete
from chilo_api.core import logger as logger
from chilo_api.core.exception import ApiException as ApiException

class Endpoint:
    SUPPORTED_METHODS: Incomplete
    def __init__(self, module, method) -> None: ...
    @property
    def module(self): ...
    @property
    def has_requirements(self): ...
    @property
    def requirements(self): ...
    @property
    def requires_auth(self): ...
    @property
    def has_required_response(self): ...
    @property
    def has_required_route(self): ...
    @property
    def required_route(self): ...
    def run(self, request, response): ...
