from chilo_api.core.json_helper import JsonHelper as JsonHelper

class Response:
    def __init__(self, **kwargs) -> None: ...
    @property
    def headers(self): ...
    @headers.setter
    def headers(self, header) -> None: ...
    @property
    def mimetype(self): ...
    @mimetype.setter
    def mimetype(self, mimetype) -> None: ...
    @property
    def cors(self): ...
    @cors.setter
    def cors(self, access) -> None: ...
    @property
    def compress(self): ...
    @compress.setter
    def compress(self, value) -> None: ...
    @property
    def code(self): ...
    @code.setter
    def code(self, code) -> None: ...
    @property
    def has_errors(self): ...
    @property
    def body(self): ...
    @body.setter
    def body(self, body) -> None: ...
    @property
    def raw(self): ...
    @property
    def server(self): ...
    def set_error(self, key_path, message) -> None: ...
