class InputArguments:
    def __init__(self, api, args) -> None: ...
    @property
    def base(self): ...
    @property
    def handlers(self): ...
    @property
    def output(self): ...
    @property
    def formats(self): ...
    @property
    def delete(self): ...
