from chilo_api.core.validator.openapi import OpenApiValidator as OpenApiValidator
from chilo_api.core.validator.schema import Schema as Schema

class Validator:
    def __init__(self, **kwargs) -> None: ...
    def auto_load(self) -> None: ...
    def request_has_security(self, request): ...
    def validate_request_with_openapi(self, request, response) -> None: ...
    def validate_request(self, request, response, requirements) -> None: ...
    def validate_response_with_openapi(self, request, response) -> None: ...
    def validate_response(self, response, requirements) -> None: ...
    @staticmethod
    def check_required_fields(response, required, sent, list_name: str = '') -> None: ...
    @staticmethod
    def check_available_fields(response, available, sent, list_name: str = '') -> None: ...
    @staticmethod
    def combine_available_with_required(requirements, required): ...
    @staticmethod
    def check_required_body(response, schema, request_body): ...
    @staticmethod
    def combine_parameters(parameters): ...
    @staticmethod
    def format_schema_error_key(schema_error): ...
    @staticmethod
    def is_json_serializable(response, request_body): ...
