from _typeshed import Incomplete

class Schema:
    def __init__(self, **kwargs) -> None: ...
    @property
    def spec(self): ...
    @property
    def paths(self): ...
    def load_schema_file(self) -> None: ...
    def get_openapi_spec(self): ...
    def get_body_spec(self, required_body: Incomplete | None = None): ...
    def get_route_spec(self, route, method): ...
