from chilo_api.cli.openapi.handler.module import HandlerModule as HandlerModule

class HandlerImporter:
    def get_modules_from_file_paths(self, file_paths, handlers_base, base_path): ...
    def import_module_from_file(self, file_path, import_path): ...
