class HandlerModule:
    def __init__(self, handler_base, file_path, module, method, base) -> None: ...
    @property
    def file_path(self): ...
    @property
    def module(self): ...
    @property
    def method(self): ...
    @property
    def operation_id(self): ...
    @property
    def route_path(self): ...
    @property
    def deprecated(self): ...
    @property
    def summary(self): ...
    @property
    def tags(self): ...
    @property
    def requires_auth(self): ...
    @property
    def required_headers(self): ...
    @property
    def available_headers(self): ...
    @property
    def required_query(self): ...
    @property
    def available_query(self): ...
    @property
    def required_path_params(self): ...
    @property
    def request_body_schema_name(self): ...
    @property
    def request_body_schema(self): ...
    @property
    def response_body_schema_name(self): ...
    @property
    def response_body_schema(self): ...
