class ServerArguments:
    def __init__(self, args, api) -> None: ...
    @property
    def host(self): ...
    @property
    def port(self): ...
    @property
    def reload(self): ...
    @property
    def verbose(self): ...
    @property
    def source(self): ...
    @property
    def timeout(self): ...
    @property
    def openapi_validate_request(self): ...
    @property
    def openapi_validate_response(self): ...
    def route(self, environ, server_response): ...
