from chilo_api.cli.openapi import generate_openapi as generate_openapi
from chilo_api.cli.server import run_server as run_server

class CliManager:
    def __init__(self) -> None: ...
    @property
    def args(self): ...
    def run(self) -> None: ...
