class ResolverImporter:
    def __init__(self, **kwargs) -> None: ...
    @staticmethod
    def import_module_from_file(file_path, import_path): ...
    @property
    def file_separator(self): ...
    @property
    def handlers(self): ...
    def clean_path(self, dirty_path): ...
    def get_file_list(self): ...
    def get_handlers_file_tree(self): ...
