class OpenAPIGenerator:
    def __init__(self, output_location) -> None: ...
    @property
    def doc(self): ...
    def delete_unused_paths(self) -> None: ...
    def add_path_and_method(self, module) -> None: ...
